// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from game.proto</summary>
public static partial class GameReflection {

  #region Descriptor
  /// <summary>File descriptor for game.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpnYW1lLnByb3RvKrgJCgVSZXFJZBILCgd0ZXN0X2lkEAASDgoKUGluZ1Jl",
          "cV9pZBABEhAKC0xvZ2luUmVxX2lkEOkHEg8KClN5bmNSZXFfaWQQ6gcSDwoK",
          "UmFua1JlcV9pZBDrBxIOCglQdnBSZXFfaWQQ7AcSEgoNUHZwUmFua1JlcV9p",
          "ZBDtBxISCg1QdnBMaXN0UmVxX2lkEO4HEhMKDlB2cEZpbnNoUmVxX2lkEO8H",
          "EhQKD1B2cFVubG9ja1JlcV9pZBDwBxIZChRPZmZlckFsbFJld2FyZFJlcV9p",
          "ZBDxBxIWChFPZmZlclJld2FyZFJlcV9pZBDyBxIbChZPZmZlckRpc3BhdGNo",
          "QWxsUmVxX2lkEPMHEhgKE09mZmVyRGlzcGF0Y2hSZXFfaWQQ9AcSFwoST2Zm",
          "ZXJSZWZyZXNoUmVxX2lkEPUHEhoKFVRpbWVEYXlSZWZyZWFzaFJlcV9pZBD2",
          "BxIbChZUaW1lSGFuZ1VwUmV3YXJkUmVxX2lkEPcHEhgKE1RhbGVudFVwTGV2",
          "ZWxSZXFfaWQQ+AcSHgoZQnV5RGlhbW9kR3Jvd3RoRnVuZFJlcV9pZBD5BxIc",
          "ChdCdXlHb2xkR3Jvd3RoRnVuZFJlcV9pZBD6BxIhChxEaWFtb2RHcm93dGhG",
          "dW5kUmV3YXJkUmVxX2lkEPsHEh8KGkdvbGRHcm93dGhGdW5kUmV3YXJkUmVx",
          "X2lkEPwHEhcKEkJ1eUVxdWlwbWVudFJlcV9pZBD9BxIbChZCdXlGcmVlRXF1",
          "aXBtZW50UmVxX2lkEP4HEhgKE1N5bmNFcXVpcG1lbnRSZXFfaWQQ/wcSFwoS",
          "QWRkRXF1aXBtZW50UmVxX2lkEIAIEhIKDUJ1eUNhcmRSZXFfaWQQgQgSFgoR",
          "QnV5RnJlZUNhcmRSZXFfaWQQgggSEwoOU3luY0NhcmRSZXFfaWQQgwgSEgoN",
          "QnV5SGVyb1JlcV9pZBCECBIVChBIZXJvVXBTdGFyUmVxX2lkEIUIEhgKE1N5",
          "bmNGb3JtYXRpb25SZXFfaWQQhggSEwoOU3luY0hlcm9SZXFfaWQQhwgSFQoQ",
          "VW5sb2NrTWluZVJlcV9pZBCICBIVChBNaW5lUmV3YXJkUmVxX2lkEIkIEhQK",
          "D1N5bmNTdGFnZVJlcV9pZBCKCBIVChBBZGREaWFtb25kUmVxX2lkEIsIEhIK",
          "DUFkZEdvbGRSZXFfaWQQjAgSEwoOU3luY0l0ZW1SZXFfaWQQjQgSFgoRTm9y",
          "bWFsRmluc2hSZXFfaWQQjggSGQoUR29sZEFCb3NzRmluc2hSZXFfaWQQjwgS",
          "GgoVQ2xpbWJUb3dlckZpbnNoUmVxX2lkEJAIEhoKFVN1cnByaXNlZFJld2Fy",
          "ZFJlcV9pZBCRCBIXChJCdXlNb250aENhcmRSZXFfaWQQkggSGgoVTW9udGhD",
          "YXJkUmV3YXJkUmVxX2lkEJMIEhoKFVR1cm50YWJsZVJld2FyZFJlcV9pZBCU",
          "CBIZChRQdnBEYWlseVJld2FyZFJlcV9pZBCVCBIWChFQdnBBZGRUaW1lc1Jl",
          "cV9pZBCWCBIVChBDaGFuZ2VOYW1lUmVxX2lkEJcIEhUKEENoYW5nZUljb25S",
          "ZXFfaWQQmAgq/AkKBlJlc3BJZBILCgdaZXJvX2lkEAASDwoLUGluZ1Jlc3Bf",
          "aWQQARIQCgxFcnJvclJlc3BfaWQQAhIRCgxMb2dpblJlc3BfaWQQ0Q8SEAoL",
          "U3luY1Jlc3BfaWQQ0g8SEAoLUmFua1Jlc3BfaWQQ0w8SDwoKUHZwUmVzcF9p",
          "ZBDUDxITCg5QdnBSYW5rUmVzcF9pZBDVDxITCg5QdnBMaXN0UmVzcF9pZBDW",
          "DxIUCg9QdnBGaW5zaFJlc3BfaWQQ1w8SFQoQUHZwVW5sb2NrUmVzcF9pZBDY",
          "DxIaChVPZmZlckFsbFJld2FyZFJlc3BfaWQQ2Q8SFwoST2ZmZXJSZXdhcmRS",
          "ZXNwX2lkENoPEhwKF09mZmVyRGlzcGF0Y2hBbGxSZXNwX2lkENsPEhkKFE9m",
          "ZmVyRGlzcGF0Y2hSZXNwX2lkENwPEhgKE09mZmVyUmVmcmVzaFJlc3BfaWQQ",
          "3Q8SGwoWVGltZURheVJlZnJlYXNoUmVzcF9pZBDeDxIcChdUaW1lSGFuZ1Vw",
          "UmV3YXJkUmVzcF9pZBDfDxIZChRUYWxlbnRVcExldmVsUmVzcF9pZBDgDxIf",
          "ChpCdXlEaWFtb2RHcm93dGhGdW5kUmVzcF9pZBDhDxIdChhCdXlHb2xkR3Jv",
          "d3RoRnVuZFJlc3BfaWQQ4g8SIgodRGlhbW9kR3Jvd3RoRnVuZFJld2FyZFJl",
          "c3BfaWQQ4w8SIAobR29sZEdyb3d0aEZ1bmRSZXdhcmRSZXNwX2lkEOQPEhgK",
          "E0J1eUVxdWlwbWVudFJlc3BfaWQQ5Q8SHAoXQnV5RnJlZUVxdWlwbWVudFJl",
          "c3BfaWQQ5g8SGQoUU3luY0VxdWlwbWVudFJlc3BfaWQQ5w8SGAoTQWRkRXF1",
          "aXBtZW50UmVzcF9pZBDoDxITCg5CdXlDYXJkUmVzcF9pZBDpDxIXChJCdXlG",
          "cmVlQ2FyZFJlc3BfaWQQ6g8SFAoPU3luY0NhcmRSZXNwX2lkEOsPEhMKDkJ1",
          "eUhlcm9SZXNwX2lkEOwPEhYKEUhlcm9VcFN0YXJSZXNwX2lkEO0PEhkKFFN5",
          "bmNGb3JtYXRpb25SZXNwX2lkEO4PEhQKD1N5bmNIZXJvUmVzcF9pZBDvDxIW",
          "ChFVbmxvY2tNaW5lUmVzcF9pZBDwDxIWChFNaW5lUmV3YXJkUmVzcF9pZBDx",
          "DxIVChBTeW5jU3RhZ2VSZXNwX2lkEPIPEhYKEUFkZERpYW1vbmRSZXNwX2lk",
          "EPMPEhMKDkFkZEdvbGRSZXNwX2lkEPQPEhQKD1N5bmNJdGVtUmVzcF9pZBD1",
          "DxIXChJOb3JtYWxGaW5zaFJlc3BfaWQQ9g8SGgoVR29sZEFCb3NzRmluc2hS",
          "ZXNwX2lkEPcPEhsKFkNsaW1iVG93ZXJGaW5zaFJlc3BfaWQQ+A8SGwoWU3Vy",
          "cHJpc2VkUmV3YXJkUmVzcF9pZBD5DxIYChNCdXlNb250aENhcmRSZXNwX2lk",
          "EPoPEhsKFk1vbnRoQ2FyZFJld2FyZFJlc3BfaWQQ+w8SGwoWVHVybnRhYmxl",
          "UmV3YXJkUmVzcF9pZBD8DxIaChVQdnBEYWlseVJld2FyZFJlc3BfaWQQ/Q8S",
          "FwoSUHZwQWRkVGltZXNSZXNwX2lkEP4PEhYKEUNoYW5nZU5hbWVSZXNwX2lk",
          "EP8PEhYKEUNoYW5nZUljb25SZXNwX2lkEIAQKjQKBENvZGUSBgoCb2sQABII",
          "CgRmYWlsEAESCwoHcmVsb2dpbhACEg0KCWNsb3NlY29ubhADKisKCU1haWxT",
          "dGF0ZRILCgduZXdtYWlsEAASCAoEcmVhZBABEgcKA2dldBACKj8KCUl0ZW1T",
          "dGF0ZRIICgRnb2xkEAASCwoHZGlhbW9uZBABEg8KC3Nob3BDYXJkS2V5EAIS",
          "CgoGcHZwS2V5EANCFAoKY29tLmNiLm1zZ0IGUEJHYW1lYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ReqId), typeof(global::RespId), typeof(global::Code), typeof(global::MailState), typeof(global::ItemState), }, null));
  }
  #endregion

}
#region Enums
public enum ReqId {
  [pbr::OriginalName("test_id")] TestId = 0,
  /// <summary>
  ///系统
  /// </summary>
  [pbr::OriginalName("PingReq_id")] PingReqId = 1,
  [pbr::OriginalName("LoginReq_id")] LoginReqId = 1001,
  [pbr::OriginalName("SyncReq_id")] SyncReqId = 1002,
  [pbr::OriginalName("RankReq_id")] RankReqId = 1003,
  [pbr::OriginalName("PvpReq_id")] PvpReqId = 1004,
  [pbr::OriginalName("PvpRankReq_id")] PvpRankReqId = 1005,
  [pbr::OriginalName("PvpListReq_id")] PvpListReqId = 1006,
  [pbr::OriginalName("PvpFinshReq_id")] PvpFinshReqId = 1007,
  [pbr::OriginalName("PvpUnlockReq_id")] PvpUnlockReqId = 1008,
  [pbr::OriginalName("OfferAllRewardReq_id")] OfferAllRewardReqId = 1009,
  [pbr::OriginalName("OfferRewardReq_id")] OfferRewardReqId = 1010,
  [pbr::OriginalName("OfferDispatchAllReq_id")] OfferDispatchAllReqId = 1011,
  [pbr::OriginalName("OfferDispatchReq_id")] OfferDispatchReqId = 1012,
  [pbr::OriginalName("OfferRefreshReq_id")] OfferRefreshReqId = 1013,
  [pbr::OriginalName("TimeDayRefreashReq_id")] TimeDayRefreashReqId = 1014,
  [pbr::OriginalName("TimeHangUpRewardReq_id")] TimeHangUpRewardReqId = 1015,
  [pbr::OriginalName("TalentUpLevelReq_id")] TalentUpLevelReqId = 1016,
  [pbr::OriginalName("BuyDiamodGrowthFundReq_id")] BuyDiamodGrowthFundReqId = 1017,
  [pbr::OriginalName("BuyGoldGrowthFundReq_id")] BuyGoldGrowthFundReqId = 1018,
  [pbr::OriginalName("DiamodGrowthFundRewardReq_id")] DiamodGrowthFundRewardReqId = 1019,
  [pbr::OriginalName("GoldGrowthFundRewardReq_id")] GoldGrowthFundRewardReqId = 1020,
  [pbr::OriginalName("BuyEquipmentReq_id")] BuyEquipmentReqId = 1021,
  [pbr::OriginalName("BuyFreeEquipmentReq_id")] BuyFreeEquipmentReqId = 1022,
  [pbr::OriginalName("SyncEquipmentReq_id")] SyncEquipmentReqId = 1023,
  [pbr::OriginalName("AddEquipmentReq_id")] AddEquipmentReqId = 1024,
  [pbr::OriginalName("BuyCardReq_id")] BuyCardReqId = 1025,
  [pbr::OriginalName("BuyFreeCardReq_id")] BuyFreeCardReqId = 1026,
  [pbr::OriginalName("SyncCardReq_id")] SyncCardReqId = 1027,
  [pbr::OriginalName("BuyHeroReq_id")] BuyHeroReqId = 1028,
  [pbr::OriginalName("HeroUpStarReq_id")] HeroUpStarReqId = 1029,
  [pbr::OriginalName("SyncFormationReq_id")] SyncFormationReqId = 1030,
  [pbr::OriginalName("SyncHeroReq_id")] SyncHeroReqId = 1031,
  [pbr::OriginalName("UnlockMineReq_id")] UnlockMineReqId = 1032,
  [pbr::OriginalName("MineRewardReq_id")] MineRewardReqId = 1033,
  [pbr::OriginalName("SyncStageReq_id")] SyncStageReqId = 1034,
  [pbr::OriginalName("AddDiamondReq_id")] AddDiamondReqId = 1035,
  [pbr::OriginalName("AddGoldReq_id")] AddGoldReqId = 1036,
  [pbr::OriginalName("SyncItemReq_id")] SyncItemReqId = 1037,
  [pbr::OriginalName("NormalFinshReq_id")] NormalFinshReqId = 1038,
  [pbr::OriginalName("GoldABossFinshReq_id")] GoldAbossFinshReqId = 1039,
  [pbr::OriginalName("ClimbTowerFinshReq_id")] ClimbTowerFinshReqId = 1040,
  [pbr::OriginalName("SurprisedRewardReq_id")] SurprisedRewardReqId = 1041,
  [pbr::OriginalName("BuyMonthCardReq_id")] BuyMonthCardReqId = 1042,
  [pbr::OriginalName("MonthCardRewardReq_id")] MonthCardRewardReqId = 1043,
  [pbr::OriginalName("TurntableRewardReq_id")] TurntableRewardReqId = 1044,
  [pbr::OriginalName("PvpDailyRewardReq_id")] PvpDailyRewardReqId = 1045,
  [pbr::OriginalName("PvpAddTimesReq_id")] PvpAddTimesReqId = 1046,
  [pbr::OriginalName("ChangeNameReq_id")] ChangeNameReqId = 1047,
  [pbr::OriginalName("ChangeIconReq_id")] ChangeIconReqId = 1048,
}

public enum RespId {
  [pbr::OriginalName("Zero_id")] ZeroId = 0,
  /// <summary>
  ///系统
  /// </summary>
  [pbr::OriginalName("PingResp_id")] PingRespId = 1,
  /// <summary>
  /// 接口返回错误
  /// </summary>
  [pbr::OriginalName("ErrorResp_id")] ErrorRespId = 2,
  [pbr::OriginalName("LoginResp_id")] LoginRespId = 2001,
  [pbr::OriginalName("SyncResp_id")] SyncRespId = 2002,
  [pbr::OriginalName("RankResp_id")] RankRespId = 2003,
  [pbr::OriginalName("PvpResp_id")] PvpRespId = 2004,
  [pbr::OriginalName("PvpRankResp_id")] PvpRankRespId = 2005,
  [pbr::OriginalName("PvpListResp_id")] PvpListRespId = 2006,
  [pbr::OriginalName("PvpFinshResp_id")] PvpFinshRespId = 2007,
  [pbr::OriginalName("PvpUnlockResp_id")] PvpUnlockRespId = 2008,
  [pbr::OriginalName("OfferAllRewardResp_id")] OfferAllRewardRespId = 2009,
  [pbr::OriginalName("OfferRewardResp_id")] OfferRewardRespId = 2010,
  [pbr::OriginalName("OfferDispatchAllResp_id")] OfferDispatchAllRespId = 2011,
  [pbr::OriginalName("OfferDispatchResp_id")] OfferDispatchRespId = 2012,
  [pbr::OriginalName("OfferRefreshResp_id")] OfferRefreshRespId = 2013,
  [pbr::OriginalName("TimeDayRefreashResp_id")] TimeDayRefreashRespId = 2014,
  [pbr::OriginalName("TimeHangUpRewardResp_id")] TimeHangUpRewardRespId = 2015,
  [pbr::OriginalName("TalentUpLevelResp_id")] TalentUpLevelRespId = 2016,
  [pbr::OriginalName("BuyDiamodGrowthFundResp_id")] BuyDiamodGrowthFundRespId = 2017,
  [pbr::OriginalName("BuyGoldGrowthFundResp_id")] BuyGoldGrowthFundRespId = 2018,
  [pbr::OriginalName("DiamodGrowthFundRewardResp_id")] DiamodGrowthFundRewardRespId = 2019,
  [pbr::OriginalName("GoldGrowthFundRewardResp_id")] GoldGrowthFundRewardRespId = 2020,
  [pbr::OriginalName("BuyEquipmentResp_id")] BuyEquipmentRespId = 2021,
  [pbr::OriginalName("BuyFreeEquipmentResp_id")] BuyFreeEquipmentRespId = 2022,
  [pbr::OriginalName("SyncEquipmentResp_id")] SyncEquipmentRespId = 2023,
  [pbr::OriginalName("AddEquipmentResp_id")] AddEquipmentRespId = 2024,
  [pbr::OriginalName("BuyCardResp_id")] BuyCardRespId = 2025,
  [pbr::OriginalName("BuyFreeCardResp_id")] BuyFreeCardRespId = 2026,
  [pbr::OriginalName("SyncCardResp_id")] SyncCardRespId = 2027,
  [pbr::OriginalName("BuyHeroResp_id")] BuyHeroRespId = 2028,
  [pbr::OriginalName("HeroUpStarResp_id")] HeroUpStarRespId = 2029,
  [pbr::OriginalName("SyncFormationResp_id")] SyncFormationRespId = 2030,
  [pbr::OriginalName("SyncHeroResp_id")] SyncHeroRespId = 2031,
  [pbr::OriginalName("UnlockMineResp_id")] UnlockMineRespId = 2032,
  [pbr::OriginalName("MineRewardResp_id")] MineRewardRespId = 2033,
  [pbr::OriginalName("SyncStageResp_id")] SyncStageRespId = 2034,
  [pbr::OriginalName("AddDiamondResp_id")] AddDiamondRespId = 2035,
  [pbr::OriginalName("AddGoldResp_id")] AddGoldRespId = 2036,
  [pbr::OriginalName("SyncItemResp_id")] SyncItemRespId = 2037,
  [pbr::OriginalName("NormalFinshResp_id")] NormalFinshRespId = 2038,
  [pbr::OriginalName("GoldABossFinshResp_id")] GoldAbossFinshRespId = 2039,
  [pbr::OriginalName("ClimbTowerFinshResp_id")] ClimbTowerFinshRespId = 2040,
  [pbr::OriginalName("SurprisedRewardResp_id")] SurprisedRewardRespId = 2041,
  [pbr::OriginalName("BuyMonthCardResp_id")] BuyMonthCardRespId = 2042,
  [pbr::OriginalName("MonthCardRewardResp_id")] MonthCardRewardRespId = 2043,
  [pbr::OriginalName("TurntableRewardResp_id")] TurntableRewardRespId = 2044,
  [pbr::OriginalName("PvpDailyRewardResp_id")] PvpDailyRewardRespId = 2045,
  [pbr::OriginalName("PvpAddTimesResp_id")] PvpAddTimesRespId = 2046,
  [pbr::OriginalName("ChangeNameResp_id")] ChangeNameRespId = 2047,
  [pbr::OriginalName("ChangeIconResp_id")] ChangeIconRespId = 2048,
}

public enum Code {
  /// <summary>
  ///成功
  /// </summary>
  [pbr::OriginalName("ok")] Ok = 0,
  /// <summary>
  ///失败
  /// </summary>
  [pbr::OriginalName("fail")] Fail = 1,
  /// <summary>
  ///重新登录(连接有效，但是并没有成功登录)
  /// </summary>
  [pbr::OriginalName("relogin")] Relogin = 2,
  /// <summary>
  ///永久关闭连接 （连接无效不要重连,例如非法连接，黑名单，被顶号....）
  /// </summary>
  [pbr::OriginalName("closeconn")] Closeconn = 3,
}

public enum MailState {
  /// <summary>
  ///0-新邮件 1-已读 2-已领 
  /// </summary>
  [pbr::OriginalName("newmail")] Newmail = 0,
  [pbr::OriginalName("read")] Read = 1,
  [pbr::OriginalName("get")] Get = 2,
}

public enum ItemState {
  [pbr::OriginalName("gold")] Gold = 0,
  [pbr::OriginalName("diamond")] Diamond = 1,
  [pbr::OriginalName("shopCardKey")] ShopCardKey = 2,
  [pbr::OriginalName("pvpKey")] PvpKey = 3,
}

#endregion


#endregion Designer generated code
